import type { Resource } from "@/components/resource-card"

export const sampleMeetups: Resource[] = [
  {
    id: "1",
    type: "meetup",
    name: "48in48: Tech and Marketing Professionals",
    description:
      "A unique meetup combining technology and marketing professionals for collaborative projects and networking opportunities.",
    tags: ["Technology", "Marketing", "Networking"],
    link: "https://www.meetup.com/48in48-tech-marketing-professionals/",
    image: "/48in48-tech-marketing-logo.png",
  },
  {
    id: "2",
    type: "meetup",
    name: "A Brighter Web",
    description: "Focused on creating a more accessible and inclusive web through design, development, and advocacy.",
    tags: ["Web Development", "Accessibility", "Design", "HTML", "CSS"],
    link: "https://www.meetup.com/abrighterweb/",
    image: "/brighter-web-accessibility-logo.png",
  },
  {
    id: "3",
    type: "meetup",
    name: "ALE-Atlanta Linux Enthusiasts",
    description:
      "Atlanta's premier Linux user group for system administrators, developers, and open source enthusiasts.",
    tags: ["Open Source", "DevOps", "Linux"],
    link: "https://www.meetup.com/ale-atlanta-linux-enthusiasts/",
    image: "/atlanta-linux-enthusiasts-logo.png",
  },
  {
    id: "4",
    type: "meetup",
    name: "A11Y Atlanta",
    description:
      "Dedicated to promoting digital accessibility and inclusive design practices in the Atlanta tech community.",
    tags: ["Accessibility", "Design", "UX"],
    link: "https://www.meetup.com/atlanta-accessibility-meetup/",
    image: "/accessibility-atlanta-logo.png",
  },
  {
    id: "5",
    type: "meetup",
    name: "Atlanta AI/ML/Data Developers Group",
    description:
      "Bringing together data scientists, machine learning engineers, and AI developers to share knowledge and collaborate.",
    tags: ["AI", "Data Science"],
    link: "https://www.meetup.com/aittg-atlanta/",
    image: "/placeholder-cieyc.png",
  },
  {
    id: "6",
    type: "meetup",
    name: "Atlanta AWS Builders",
    description: "Community of AWS enthusiasts sharing best practices, architecture patterns, and cloud solutions.",
    tags: ["Cloud", "DevOps"],
    link: "https://www.meetup.com/atlanta-aws-builders/",
    image: "/atlanta-aws-builders-cloud-logo.png",
  },
  {
    id: "7",
    type: "meetup",
    name: "Atlanta Azure Data User Group",
    description: "Focus on Microsoft Azure data services, analytics, and business intelligence solutions.",
    tags: ["Cloud", "Data Science"],
    link: "https://www.meetup.com/atlanta-azure-data-user-group/",
    image: "/atlanta-azure-data-user-group-logo.png",
  },
  {
    id: "8",
    type: "meetup",
    name: "Atlanta Computer Club DOT Com",
    description:
      "General technology meetup covering various aspects of computing, programming, and digital innovation.",
    tags: ["Technology", "Programming"],
    link: "https://www.meetup.com/atlanta-computer-club-dot-com/",
    image: "/atlanta-computer-club-logo.png",
  },
  {
    id: "9",
    type: "meetup",
    name: "Atlanta Drupal Users Group",
    description:
      "Community for Drupal developers, site builders, and content managers sharing knowledge and best practices.",
    tags: ["Web Development", "CMS"],
    link: "https://www.meetup.com/drupalatlanta/",
    image: "/atlanta-drupal-users-group-logo.png",
  },
  {
    id: "10",
    type: "meetup",
    name: "Atlanta Elixir Meetup",
    description: "Functional programming enthusiasts exploring Elixir, Phoenix, and the BEAM ecosystem.",
    tags: ["Programming Languages", "Backend", "Elixir"],
    link: "https://www.meetup.com/atlantaelixir/",
    image: "/atlanta-elixir-fp-logo.png",
  },
  {
    id: "11",
    type: "meetup",
    name: "Atlanta Functional Programming Meetup",
    description: "Exploring functional programming concepts, languages, and paradigms with like-minded developers.",
    tags: ["Programming Languages"],
    link: "https://www.meetup.com/atlanta-functional-programming-meetup/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "12",
    type: "meetup",
    name: "Atlanta Generative AI Group",
    description: "Cutting-edge discussions on generative AI, large language models, and AI applications in business.",
    tags: ["AI", "Business"],
    link: "https://www.meetup.com/atl-ai/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "13",
    type: "meetup",
    name: "Atlanta Java Users Group",
    description: "Long-running Java community covering enterprise development, Spring framework, and JVM technologies.",
    tags: ["Programming Languages", "Backend", "Java", "Spring"],
    link: "https://www.meetup.com/atlantajug/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "14",
    type: "meetup",
    name: "Atlanta Low-Key Data Meetup",
    description:
      "Relaxed environment for data professionals to discuss analytics, visualization, and data engineering.",
    tags: ["Data Science"],
    link: "https://www.meetup.com/atlanta-low-key-data-meetup/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "15",
    type: "meetup",
    name: "Atlanta Metro Code and Coffee",
    description: "Early morning coding sessions and networking at the Computer Museum of America.",
    tags: ["Programming", "Networking"],
    link: "https://www.meetup.com/atlanta-metro-code-and-coffee/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "16",
    type: "meetup",
    name: "Atlanta Minorities in Technology",
    description:
      "Supporting underrepresented groups in technology through mentorship, networking, and career development.",
    tags: ["Diversity", "Careers", "Networking"],
    link: "https://www.meetup.com/atlanta-minorities-in-technology/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "17",
    type: "meetup",
    name: "Atlanta NoSQL Meetup Group",
    description: "Exploring non-relational databases, document stores, and modern data persistence solutions.",
    tags: ["Database", "Backend"],
    link: "https://www.meetup.com/atlanta-nosql-meetup-group/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "18",
    type: "meetup",
    name: "Atlanta Ruby Meetup Group",
    description: "Ruby and Rails developers sharing knowledge, best practices, and building community connections.",
    tags: ["Programming Languages", "Web Development", "Ruby", "Rails"],
    link: "https://www.meetup.com/atlantaruby/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "19",
    type: "meetup",
    name: "Atlanta Salesforce Saturday Meetup",
    description: "Weekend sessions for Salesforce administrators, developers, and users to learn and network.",
    tags: ["Business", "CRM"],
    link: "https://www.meetup.com/atlanta-salesforce-saturday-meetup/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "20",
    type: "meetup",
    name: "Atlanta Tech + Startups Social in Midtown",
    description:
      "Casual networking for tech professionals and startup enthusiasts at Rowdy Tiger Whiskey Bar & Kitchen.",
    tags: ["Startups", "Networking"],
    link: "https://www.meetup.com/atlanta-tech-startups-party-in-midtown/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "21",
    type: "meetup",
    name: "Atlanta Tech Meetup",
    description:
      "General technology meetup at Atlanta Tech Park covering various tech topics and networking opportunities.",
    tags: ["Technology", "Networking"],
    link: "https://www.meetup.com/atl-tech-meetup/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "22",
    type: "meetup",
    name: "Atlanta Tech Meetup Group",
    description: "Broad technology community discussing trends, innovations, and career opportunities in tech.",
    tags: ["Technology", "Careers"],
    link: "https://www.meetup.com/atl-technology-meetup-group/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "23",
    type: "meetup",
    name: "Atlanta Tech Talks",
    description: "Technical presentations and discussions hosted at FanDuel covering various technology topics.",
    tags: ["Technology", "Education"],
    link: "https://www.meetup.com/atlanta-tech-talks/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "24",
    type: "meetup",
    name: "Atlanta Vue.js Meetup",
    description: "Vue.js developers and enthusiasts sharing knowledge about the progressive JavaScript framework.",
    tags: ["Frontend", "Web Development", "JavaScript", "Vue"],
    link: "https://www.meetup.com/atlanta-vue-js-meetup/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "25",
    type: "meetup",
    name: "Atlanta Women in AI",
    description: "Supporting women in artificial intelligence through education, networking, and career advancement.",
    tags: ["Diversity", "AI"],
    link: "https://www.meetup.com/atlanta-women-in-ai/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "26",
    type: "meetup",
    name: "Atlanta WordPress Users Group",
    description: "WordPress developers, designers, and users sharing tips, plugins, and best practices.",
    tags: ["Web Development", "CMS", "PHP", "WordPress"],
    link: "https://www.meetup.com/wordpress-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "27",
    type: "meetup",
    name: "ATL BitLab",
    description:
      "Creative technology meetup also hosting ATL Designers events, focusing on digital innovation and design.",
    tags: ["Design", "Technology"],
    link: "https://www.meetup.com/atlbitlab/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "28",
    type: "meetup",
    name: "BDPA Atlanta",
    description: "Black Data Processing Associates promoting careers in information technology for African Americans.",
    tags: ["Diversity", "Careers"],
    link: "https://www.meetup.com/bdpa-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "29",
    type: "meetup",
    name: "BlackHack Society - Atlanta",
    description: "Cybersecurity community focused on ethical hacking, penetration testing, and information security.",
    tags: ["Cybersecurity"],
    link: "https://www.meetup.com/blackhack-society-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "30",
    type: "meetup",
    name: "Casual Coding",
    description: "Relaxed coding meetup for developers of all levels to work on projects and share knowledge.",
    tags: ["Programming"],
    link: "https://www.meetup.com/casualcoding/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "31",
    type: "meetup",
    name: "Civic Tech Atlanta",
    description:
      "Using technology to improve civic engagement and solve community problems through collaborative projects.",
    tags: ["Civic Tech", "Community"],
    link: "https://www.meetup.com/civictechatlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "32",
    type: "meetup",
    name: "Cherokee Tech Community",
    description: "Technology community serving the Cherokee County area with networking and learning opportunities.",
    tags: ["Technology", "Networking"],
    link: "https://www.meetup.com/cherokee-tech-community/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "33",
    type: "meetup",
    name: "Conyers WordPress Meetup",
    description: "WordPress community in Conyers focusing on development, design, and content management.",
    tags: ["Web Development", "CMS", "PHP", "WordPress"],
    link: "https://www.meetup.com/conyers-wordpress-meetup/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "34",
    type: "meetup",
    name: "CTO Corner: Tech Guidance for Business Leaders",
    description: "Technology leadership discussions for CTOs, tech executives, and business leaders.",
    tags: ["Leadership", "Business"],
    link: "https://www.meetup.com/cto-corner-tech-guidance-for-business-leaders/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "35",
    type: "meetup",
    name: "DBA Fundamentals Group",
    description:
      "Database administrators sharing knowledge about database management, optimization, and best practices.",
    tags: ["Database"],
    link: "https://www.meetup.com/dba-fundamentals-group/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "36",
    type: "meetup",
    name: "Decatur Lunch Bunch A Tech Meetup",
    description: "Lunchtime tech meetup in Decatur for casual networking and technology discussions.",
    tags: ["Technology", "Networking"],
    link: "https://www.meetup.com/decatur-lunch-bunch-a-tech-meetup/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "37",
    type: "meetup",
    name: "Ethical Hackers, Penetration Testers, & Information Security",
    description:
      "Cybersecurity professionals focused on ethical hacking, penetration testing, and information security.",
    tags: ["Cybersecurity"],
    link: "https://www.meetup.com/ethical-hackers/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "38",
    type: "meetup",
    name: "Flutter Atlanta",
    description: "Mobile developers using Flutter framework for cross-platform app development.",
    tags: ["Mobile Development", "Flutter", "Dart"],
    link: "https://www.meetup.com/flutter-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "39",
    type: "meetup",
    name: "Free Code Camp Atlanta",
    description: "Local chapter of freeCodeCamp providing support and community for aspiring developers.",
    tags: ["Education", "Web Development", "JavaScript", "HTML", "CSS"],
    link: "https://www.facebook.com/groups/free.code.camp.atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "40",
    type: "meetup",
    name: "GenAI Executives ATL",
    description: "Executive-level discussions on generative AI strategy, implementation, and business impact.",
    tags: ["AI", "Business", "Leadership"],
    link: "https://www.meetup.com/genaiexecsandpratitioners/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "41",
    type: "meetup",
    name: "Google Cloud User Group - Atlanta",
    description:
      "Google Cloud Platform users sharing knowledge about cloud services, architecture, and best practices.",
    tags: ["Cloud"],
    link: "https://www.meetup.com/google-cloud-user-group-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "42",
    type: "meetup",
    name: "Google Developer Groups (GDG) Atlanta",
    description: "Official Google Developer Group covering Android, web technologies, and Google developer tools.",
    tags: ["Mobile Development", "Web Development", "Android", "Kotlin", "Java"],
    link: "https://www.meetup.com/google-developer-groups-gdg-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "43",
    type: "meetup",
    name: "IxDA Atlanta",
    description:
      "Interaction Design Association chapter focusing on user experience, design thinking, and digital interactions.",
    tags: ["UX", "Design"],
    link: "https://www.meetup.com/ixdaatlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "44",
    type: "meetup",
    name: "Junior Zeros - Gen-Z/Zillennials Tech Media",
    description: "Tech media community for Gen-Z and Millennial professionals in technology and digital media.",
    tags: ["Media", "Community"],
    link: "https://www.meetup.com/juniorzeros/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "45",
    type: "meetup",
    name: "Kong/ATLANTA",
    description: "API gateway and microservices community focused on Kong and modern API management.",
    tags: ["Backend", "APIs"],
    link: "https://www.meetup.com/kong-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "46",
    type: "meetup",
    name: "Ladies That UX ATL",
    description: "Women in UX design community providing networking, mentorship, and professional development.",
    tags: ["Diversity", "UX", "Design"],
    link: "https://www.meetup.com/ladies-that-ux-atl/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "47",
    type: "meetup",
    name: "Modern Web ATL - Alpharetta",
    description: "Modern web development practices, frameworks, and technologies in the Alpharetta area.",
    tags: ["Web Development", "Frontend", "JavaScript", "React", "Vue", "Angular"],
    link: "https://www.meetup.com/modernwebatl/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "48",
    type: "meetup",
    name: "NW Atlanta Amazon Web Services Meetup",
    description: "AWS community in Northwest Atlanta focusing on cloud architecture and Amazon Web Services.",
    tags: ["Cloud"],
    link: "https://www.meetup.com/nw-atlanta-amazon-web-services-meetup/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "49",
    type: "meetup",
    name: "Obsidi® Tech Talks - Black Tech Professionals - Atlanta GA",
    description: "Professional development and networking for Black technology professionals and entrepreneurs.",
    tags: ["Diversity", "Careers", "Entrepreneurship"],
    link: "https://www.meetup.com/obsidi-tech-talks-black-tech-professionals-meetup-group/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "50",
    type: "meetup",
    name: "OTP Developers",
    description:
      "Outside the Perimeter developers community serving suburban Atlanta with coding and networking events.",
    tags: ["Programming", "Community"],
    link: "https://www.meetup.com/otpdevs/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "51",
    type: "meetup",
    name: "OWASP Atlanta Chapter",
    description:
      "Open Web Application Security Project chapter focused on web application security and best practices.",
    tags: ["Cybersecurity", "Web Development"],
    link: "https://www.meetup.com/owasp-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "52",
    type: "meetup",
    name: "Platform Engineers Atlanta",
    description: "Platform engineering community focusing on infrastructure, DevOps, and developer experience.",
    tags: ["DevOps", "Infrastructure"],
    link: "https://www.meetup.com/platform-engineers-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "53",
    type: "meetup",
    name: "PyAtl: Atlanta Python Programmers",
    description: "Atlanta's Python community covering web development, data science, automation, and more.",
    tags: ["Programming Languages", "Data Science", "Python", "Django", "Flask"],
    link: "https://www.meetup.com/python-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "54",
    type: "meetup",
    name: "PyData Atlanta",
    description: "Python data science community focusing on analytics, machine learning, and data visualization.",
    tags: ["Data Science", "AI", "Python"],
    link: "https://www.meetup.com/pydata-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "55",
    type: "meetup",
    name: "React ATL",
    description: "React developers community sharing knowledge about the popular JavaScript library and ecosystem.",
    tags: ["Frontend", "Web Development", "JavaScript", "React"],
    link: "https://www.meetup.com/react-atl/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "56",
    type: "meetup",
    name: "React Robins (formerly React Ladies)",
    description:
      "Inclusive React community supporting developers of all backgrounds in learning and growing with React.",
    tags: ["Diversity", "Frontend", "JavaScript", "React"],
    link: "https://www.meetup.com/react-ladies/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "57",
    type: "meetup",
    name: "REFACTR.TECH",
    description: "Conference and community focused on diversity and inclusion in technology and software development.",
    tags: ["Diversity", "Programming"],
    link: "https://www.meetup.com/refactr-tech/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "58",
    type: "meetup",
    name: "RIoT Atlanta",
    description: "Regional Internet of Things community exploring connected devices, sensors, and IoT applications.",
    tags: ["Hardware", "IoT"],
    link: "https://www.meetup.com/riot-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "59",
    type: "meetup",
    name: "Software Crafters Atlanta",
    description:
      "Software craftsmanship community focused on clean code, best practices, and professional development.",
    tags: ["Programming", "Careers"],
    link: "https://www.meetup.com/software-craftsmanship-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "60",
    type: "meetup",
    name: "Tech in Motion: Atlanta",
    description:
      "Technology networking events connecting professionals across various tech disciplines and industries.",
    tags: ["Technology", "Networking"],
    link: "https://www.meetup.com/techinmotionatlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "61",
    type: "meetup",
    name: "tech404",
    description:
      "Atlanta's largest tech community with online chat and regular meetups covering all aspects of technology.",
    tags: ["Technology", "Community"],
    link: "https://www.meetup.com/tech404/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "62",
    type: "meetup",
    name: "Technologists of Color",
    description:
      "Supporting technologists of color through community building, mentorship, and professional development.",
    tags: ["Diversity", "Careers"],
    link: "https://www.meetup.com/technologists/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "63",
    type: "meetup",
    name: "The Atlanta Game Developer Meetup Group",
    description:
      "Game developers community covering game design, programming, art, and the business of game development.",
    tags: ["Game Development", "Programming"],
    link: "https://www.meetup.com/gamedev-150/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "64",
    type: "meetup",
    name: "The Atlanta JavaScript Meetup Group",
    description: "JavaScript developers community covering frameworks, libraries, and modern JavaScript development.",
    tags: ["Frontend", "Backend", "Web Development", "JavaScript", "Node.js"],
    link: "https://www.meetup.com/atlantajavascript/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "65",
    type: "meetup",
    name: "The Ubuntu TechHive North America",
    description: "Ubuntu and Linux community focusing on open source technologies and Ubuntu ecosystem.",
    tags: ["Open Source"],
    link: "https://www.meetup.com/the-ubuntu-techhive-north-america/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "66",
    type: "meetup",
    name: "Tyrannosaurus Tech",
    description: "Fun and engaging tech meetup with a playful approach to technology discussions and networking.",
    tags: ["Technology", "Networking"],
    link: "https://www.meetup.com/tyrannosaurus-tech-atlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "67",
    type: "meetup",
    name: "WordPress Cobb (Metro Atlanta) Users Group",
    description: "WordPress community serving Cobb County and Metro Atlanta with development and design focus.",
    tags: ["Web Development", "CMS", "PHP", "WordPress"],
    link: "https://www.meetup.com/wpatlanta/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "68",
    type: "meetup",
    name: "75 south devs",
    description:
      "Developer community connecting through LinkedIn, fostering collaboration and knowledge sharing among software developers in the Atlanta area.",
    tags: ["Programming", "Community", "Networking", "LinkedIn"],
    link: "https://www.linkedin.com/groups/13257067/",
    image: "/75-south-devs-logo.png",
  },
].sort((a, b) => a.name.localeCompare(b.name))

export const sampleConferences: Resource[] = [
  {
    id: "1",
    type: "conference",
    name: "Atlanta Developers' Conference",
    description:
      "Premier developer conference bringing together Atlanta's tech community for learning, networking, and sharing the latest in software development.",
    tags: ["Programming", "Web Development", "Networking"],
    link: "https://www.atldevcon.com/",
    image: "/atlanta-developers-conference.png",
    conferenceDate: "2026-09-15",
  },
  {
    id: "2",
    type: "conference",
    name: "Connect.Tech",
    description:
      "The largest frontend conference in the Southeast, featuring talks on React, Angular, Vue, mobile development, and emerging web technologies.",
    tags: ["Frontend", "React", "Angular", "Vue", "Mobile Development", "JavaScript"],
    link: "https://connect.tech/",
    cfpDate: "2026-06-15",
    conferenceDate: "2026-10-17",
    image: "/connect-tech-logo.png",
  },
  {
    id: "3",
    type: "conference",
    name: "DevNexus",
    description:
      "Premier Java and JVM conference focusing on Spring, microservices, cloud-native development, and enterprise Java practices.",
    tags: ["Java", "Spring", "Backend", "Enterprise", "Cloud"],
    link: "https://devnexus.com/",
    cfpDate: "2026-09-30",
    conferenceDate: "2026-04-08",
    image: "/devnexus-java-conference.png",
  },
  {
    id: "4",
    type: "conference",
    name: "DevFest Atlanta",
    description:
      "Google Developer Groups community-led conference covering Android, web technologies, machine learning, and Google Cloud Platform.",
    tags: ["Android", "Web Development", "AI", "Cloud", "Mobile Development"],
    link: "https://gdg.community.dev/gdg-atlanta/",
    conferenceDate: "2026-11-08",
    image: "/devfest-atlanta-gdg.png",
  },
  {
    id: "5",
    type: "conference",
    name: "DevOps Days Atlanta",
    description:
      "Community-driven conference focusing on DevOps practices, automation, continuous integration, and infrastructure as code.",
    tags: ["DevOps", "Cloud", "Infrastructure", "Automation"],
    link: "https://devopsdays.org/",
    conferenceDate: "2026-05-20",
    image: "/devops-days-atlanta.png",
  },
  {
    id: "6",
    type: "conference",
    name: "DrupalCon Atlanta",
    description:
      "The premier Drupal conference bringing together developers, site builders, and digital strategists for the latest in Drupal development.",
    tags: ["Drupal", "CMS", "Web Development", "PHP"],
    link: "https://events.drupal.org/atlanta2026",
    conferenceDate: "2026-05-05",
    image: "/drupalcon-atlanta.png",
  },
  {
    id: "7",
    type: "conference",
    name: "FutureCon",
    description:
      "Forward-thinking technology conference exploring emerging trends, artificial intelligence, blockchain, and the future of digital innovation.",
    tags: ["AI", "Blockchain", "Emerging Tech", "Innovation"],
    link: "https://futureconevents.com/",
    conferenceDate: "2026-08-12",
    image: "/futurecon-tech-innovation.png",
  },
  {
    id: "8",
    type: "conference",
    name: "GitKon",
    description:
      "Git and version control conference covering advanced Git workflows, collaboration strategies, and modern development practices.",
    tags: ["Git", "DevOps", "Programming", "Collaboration"],
    link: "https://gitkon.com/",
    conferenceDate: "2026-06-25",
    image: "/gitkon-version-control.png",
  },
  {
    id: "9",
    type: "conference",
    name: "Virtual DevEx & AI Conference",
    description:
      "Virtual conference focused on developer experience, AI-powered development tools, and the future of software engineering.",
    tags: ["AI", "Developer Tools", "Programming", "Virtual"],
    link: "https://virtualdevex.com/",
    conferenceDate: "2026-07-15",
    image: "/virtual-devex-ai-conference.png",
  },
  {
    id: "10",
    type: "conference",
    name: "Hacker Halted",
    description:
      "Premier cybersecurity conference featuring ethical hacking, penetration testing, incident response, and information security best practices.",
    tags: ["Cybersecurity", "Ethical Hacking", "Security"],
    link: "https://hackerhalted.com/",
    conferenceDate: "2026-10-28",
    image: "/hacker-halted-cybersecurity.png",
  },
  {
    id: "11",
    type: "conference",
    name: "KubeCon + CloudNativeCon",
    description:
      "The flagship conference for Kubernetes and cloud-native technologies, covering container orchestration, microservices, and cloud infrastructure.",
    tags: ["Kubernetes", "Cloud", "DevOps", "Containers"],
    link: "https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america-2026/",
    cfpDate: "2026-07-01",
    conferenceDate: "2026-11-12",
    image: "/kubecon-cloudnative.png",
  },
  {
    id: "12",
    type: "conference",
    name: "ProductCamp Atlanta",
    description:
      "Unconference-style event for product managers, designers, and entrepreneurs to share insights on product development and strategy.",
    tags: ["Product Management", "Design", "UX", "Business"],
    link: "https://pcampatl.com/",
    conferenceDate: "2026-03-22",
    image: "/productcamp-atlanta.png",
  },
  {
    id: "13",
    type: "conference",
    name: "Render ATL",
    description:
      "Design and frontend conference celebrating creativity in web design, user experience, and digital storytelling.",
    tags: ["Design", "Frontend", "UX", "Web Development"],
    link: "https://www.renderatl.com/",
    cfpDate: "2026-05-30",
    conferenceDate: "2026-08-28",
    image: "/render-atl-design.png",
  },
  {
    id: "14",
    type: "conference",
    name: "Snowflake World Tour Atlanta",
    description:
      "Data cloud conference focusing on modern data architecture, analytics, machine learning, and data-driven business transformation.",
    tags: ["Data Science", "Analytics", "Cloud", "AI"],
    link: "https://www.snowflake.com/events/snowflake-world-tour-atlanta/",
    conferenceDate: "2026-09-10",
    image: "/snowflake-world-tour.png",
  },
  {
    id: "15",
    type: "conference",
    name: "SOSS Fusion",
    description:
      "Open source security conference addressing supply chain security, vulnerability management, and secure software development practices.",
    tags: ["Open Source", "Cybersecurity", "Security"],
    link: "https://events.linuxfoundation.org/soss-fusion/",
    conferenceDate: "2026-04-15",
    image: "/soss-fusion-security.png",
  },
  {
    id: "16",
    type: "conference",
    name: "Super Computing (SC)",
    description:
      "The International Conference for High Performance Computing, Networking, Storage, and Analysis - the premier global event for HPC professionals.",
    tags: ["High Performance Computing", "Networking", "Research"],
    link: "https://supercomputing.org/",
    conferenceDate: "2026-11-16",
    image: "/supercomputing-hpc.png",
  },
  {
    id: "17",
    type: "conference",
    name: "TECHSPO Atlanta",
    description:
      "Technology expo and conference showcasing the latest innovations in AI, IoT, blockchain, cybersecurity, and digital transformation.",
    tags: ["Technology", "AI", "IoT", "Blockchain", "Innovation"],
    link: "https://techspoatlanta.com/",
    conferenceDate: "2026-06-18",
    image: "/techspo-atlanta.png",
  },
]

export const sampleOnlineResources: Resource[] = [
  {
    id: "1",
    type: "online",
    name: "100 Devs",
    description:
      "Free full-stack web development bootcamp with live classes, community support, and job placement assistance. Learn HTML, CSS, JavaScript, and more.",
    tags: ["Bootcamp", "Full-Stack", "Free/Low-Cost", "Community", "JavaScript", "HTML", "CSS"],
    link: "https://leonnoel.com/100devs/",
    image: "/100devs-logo.png",
  },
  {
    id: "2",
    type: "online",
    name: "AnitaB.org",
    description:
      "Global nonprofit organization connecting, inspiring, and guiding women in computing and organizations that view technology innovation as a strategic imperative.",
    tags: ["Diversity & Inclusion", "Women in Tech", "Community"],
    link: "https://anitab.org/",
    image: "/anitab-org-women-in-tech-logo.png",
  },
  {
    id: "3",
    type: "online",
    name: "ATL Gamedevs",
    description:
      "Atlanta game development community connecting local game developers, artists, and designers through events, resources, and collaboration opportunities.",
    tags: ["Game Development", "Community", "Design"],
    link: "https://atlgamedevs.com",
    image: "/placeholder-j37cd.png",
  },
  {
    id: "4",
    type: "online",
    name: "Atlanta OTP Developers",
    description:
      "Outside the Perimeter developers community serving suburban Atlanta developers through Slack workspace and networking events.",
    tags: ["Community", "Programming", "Networking & Events"],
    link: "http://otpdevs.slack.com/",
    image: "/otp-developers-atlanta-logo.png",
  },
  {
    id: "5",
    type: "online",
    name: "Baddies in Tech",
    description:
      "Community empowering women of color in technology through networking, mentorship, and professional development opportunities.",
    tags: ["Diversity & Inclusion", "Women in Tech", "Community"],
    link: "https://www.baddiesintech.com/",
    image: "/baddies-in-tech-logo.png",
  },
  {
    id: "6",
    type: "online",
    name: "Black Girls CODE",
    description:
      "Organization dedicated to showing the world that black girls can code and do so much more by providing technology education and exposure.",
    tags: ["Diversity & Inclusion", "Education & Learning", "Youth", "Programming"],
    link: "https://www.wearebgc.org/",
    image: "/black-girls-code-education-logo.png",
  },
  {
    id: "7",
    type: "online",
    name: "Black Men in Tech",
    description:
      "Community focused on increasing representation and success of Black men in technology through networking, mentorship, and career development.",
    tags: ["Diversity & Inclusion", "Community", "Networking & Events"],
    link: "https://www.blkmenintech.com/",
    image: "/placeholder-regzd.png",
  },
  {
    id: "8",
    type: "online",
    name: "Black Python Devs",
    description:
      "Community of Black Python developers sharing knowledge, resources, and opportunities in Python programming and data science.",
    tags: ["Diversity & Inclusion", "Python", "Programming Languages", "Data Science"],
    link: "https://blackpythondevs.com/index.html",
    image: "/black-python-developers-logo.png",
  },
  {
    id: "9",
    type: "online",
    name: "Blacks in Technology (BIT)",
    description:
      "Global community focused on 'Stomping the Divide' by establishing a blueprint of world-class technical excellence and innovation.",
    tags: ["Diversity & Inclusion", "Community"],
    link: "https://www.blacksintechnology.net/",
    image: "/placeholder-wuugd.png",
  },
  {
    id: "10",
    type: "online",
    name: "Code & Conscience",
    description:
      "Community exploring the intersection of technology and social impact, focusing on ethical coding and responsible innovation.",
    tags: ["Ethics", "Social Impact", "Community"],
    link: "https://code-conscience.kit.com/profile",
    image: "/code-conscience-logo.png",
  },
  {
    id: "11",
    type: "online",
    name: "Codedex Community",
    description:
      "Interactive coding community with gamified learning experiences, challenges, and peer support for aspiring developers.",
    tags: ["Community", "Interactive Learning", "Programming"],
    link: "https://www.codedx.io/community",
    image: "/codedx-logo.png",
  },
  {
    id: "12",
    type: "online",
    name: "Commit Your Code",
    description:
      "Platform connecting developers with open source projects and providing resources for contributing to meaningful software projects.",
    tags: ["Open Source", "Community", "Programming"],
    link: "https://www.commityourcode.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "13",
    type: "online",
    name: "Diversify Tech",
    description:
      "Newsletter and community providing career opportunities, resources, and support for underrepresented groups in technology.",
    tags: ["Diversity & Inclusion", "Job Opportunities"],
    link: "https://www.diversifytech.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "14",
    type: "online",
    name: "Forage",
    description:
      "Virtual work experience platform offering free job simulations from top companies to help students and graduates build practical skills.",
    tags: ["Virtual Experience", "Skills Development"],
    link: "https://www.theforage.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "15",
    type: "online",
    name: "FreeCodeCamp",
    description:
      "Learn to code for free with interactive lessons, projects, and certifications in web development, data science, and machine learning.",
    tags: ["Free/Low-Cost", "Certifications", "Interactive Learning", "Projects", "JavaScript", "HTML", "CSS"],
    link: "https://www.freecodecamp.org/",
    image: "/freecodecamp-coding-education.png",
  },
  {
    id: "16",
    type: "online",
    name: "Frontend Queens",
    description:
      "Community empowering women and non-binary individuals in frontend development through mentorship, resources, and networking.",
    tags: ["Diversity & Inclusion", "Frontend", "Community", "Mentorship & Guidance"],
    link: "https://www.frontendqueens.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "17",
    type: "online",
    name: "Girl Develop It",
    description:
      "Nonprofit organization providing affordable programs for adult women and non-binary individuals to learn software development skills.",
    tags: ["Diversity & Inclusion", "Education & Learning", "Programming", "Free/Low-Cost"],
    link: "https://girldevelopit.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "18",
    type: "online",
    name: "Google Women Techmakers",
    description:
      "Google's program providing visibility, community, and resources for women in technology through events, mentorship, and scholarships.",
    tags: ["Diversity & Inclusion", "Women in Tech", "Mentorship & Guidance"],
    link: "https://developers.google.com/womentechmakers",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "19",
    type: "online",
    name: "Hypepotamus",
    description:
      "Atlanta-based media company covering startups, entrepreneurship, and innovation in the Southeast tech ecosystem.",
    tags: ["Media", "Startups"],
    link: "https://hypepotamus.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "20",
    type: "online",
    name: "Latinas in Tech",
    description:
      "Global community connecting and empowering Latinas in technology through networking, mentorship, and professional development.",
    tags: ["Diversity & Inclusion", "Community", "Networking & Events"],
    link: "https://latinasintech.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "21",
    type: "online",
    name: "Latinos in Tech",
    description:
      "Community building a stronger network of Latino professionals in technology through events, mentorship, and career opportunities.",
    tags: ["Diversity & Inclusion", "Community", "Networking & Events"],
    link: "https://www.latinosin.tech/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "22",
    type: "online",
    name: "Learn with Jason",
    description:
      "Educational platform featuring live coding streams, tutorials, and resources for web development and modern JavaScript frameworks.",
    tags: ["Education & Learning", "Live Coding", "JavaScript", "Web Development"],
    link: "https://www.learnwithjason.dev/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "23",
    type: "online",
    name: "Mentor Me Collective",
    description:
      "Platform connecting mentors and mentees in technology, providing structured mentorship programs and career guidance.",
    tags: ["Mentorship & Guidance", "Community"],
    link: "https://www.mentormecollective.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "24",
    type: "online",
    name: "Out in Tech",
    description:
      "Global community uniting LGBTQ+ tech professionals through networking, mentorship, and advocacy for inclusive workplaces.",
    tags: ["Diversity & Inclusion", "LGBTQ+", "Community", "Networking & Events"],
    link: "https://outintech.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "25",
    type: "online",
    name: "Power to Fly",
    description:
      "Platform connecting women and underrepresented groups with remote work opportunities and career development resources.",
    tags: ["Diversity & Inclusion", "Remote Work", "Women in Tech"],
    link: "https://powertofly.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "26",
    type: "online",
    name: "Product ATL",
    description:
      "Atlanta product management community providing networking, education, and career development for product professionals.",
    tags: ["Product Management", "Community"],
    link: "https://www.productatl.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "27",
    type: "online",
    name: "Product Coffee",
    description:
      "Community for product managers and designers to connect over coffee, share insights, and discuss product strategy and design.",
    tags: ["Product Management", "Design", "Community", "Networking & Events"],
    link: "https://productcoffee.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "28",
    type: "online",
    name: "RefCode",
    description:
      "Platform helping developers find referrals and job opportunities through community connections and networking.",
    tags: ["Job Opportunities", "Networking & Events"],
    link: "https://refcode.org/pages/index.html",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "29",
    type: "online",
    name: "Resilient Coders",
    description:
      "Nonprofit training people of color for high-growth careers as software engineers, focusing on economic empowerment through coding.",
    tags: ["Diversity & Inclusion", "Education & Learning", "Bootcamp"],
    link: "https://www.resilientcoders.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "30",
    type: "online",
    name: "Rewriting the Code",
    description:
      "Community supporting college women and non-binary students in computer science through mentorship, internships, and career opportunities.",
    tags: ["Diversity & Inclusion", "Mentorship & Guidance", "Computer Science"],
    link: "https://rewritingthecode.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "31",
    type: "online",
    name: "Society of Hispanic Professional Engineers (SHPE)",
    description:
      "Organization empowering the Hispanic community to realize their fullest potential and impact the world through STEM awareness, access, support, and development.",
    tags: ["Diversity & Inclusion", "Engineering", "STEM", "Community"],
    link: "https://shpe.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "32",
    type: "online",
    name: "Startup Oasis",
    description:
      "Atlanta startup community providing resources, events, and networking opportunities for entrepreneurs and startup enthusiasts.",
    tags: ["Startups", "Entrepreneurship", "Community"],
    link: "https://www.startupoasis.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "33",
    type: "online",
    name: "Technology Association of Georgia (TAG)",
    description:
      "Georgia's leading technology industry association driving growth, innovation, and community building in the state's tech sector.",
    tags: ["Industry Association"],
    link: "https://www.tagonline.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "34",
    type: "online",
    name: "Tech Equity Collective",
    description:
      "Organization working to create a more equitable and inclusive tech industry through advocacy, education, and community building.",
    tags: ["Diversity & Inclusion", "Advocacy", "Community"],
    link: "https://www.techequitycollective.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "35",
    type: "online",
    name: "Tech Fleet",
    description:
      "Community connecting tech professionals through networking events, career resources, and professional development opportunities.",
    tags: ["Community", "Networking & Events"],
    link: "https://techfleet.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "36",
    type: "online",
    name: "Techqueria",
    description:
      "Largest community of Latinx professionals in tech, providing networking, mentorship, and career development opportunities.",
    tags: ["Diversity & Inclusion", "Latinx", "Community"],
    link: "https://techqueria.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "37",
    type: "online",
    name: "Techsgiving",
    description:
      "Annual conference and community celebrating diversity in technology, featuring speakers, workshops, and networking opportunities.",
    tags: ["Diversity & Inclusion", "Community", "Networking & Events"],
    link: "https://www.techsgiving.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "38",
    type: "online",
    name: "TEDxAtlanta",
    description:
      "Atlanta's TEDx event featuring innovative speakers sharing ideas worth spreading in technology, design, entertainment, and more.",
    tags: ["Speaking"],
    link: "https://www.tedxatlanta.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "39",
    type: "online",
    name: "The Knowledge House",
    description:
      "Nonprofit providing tech training and career development for underrepresented young adults in underserved communities.",
    tags: ["Diversity & Inclusion", "Education & Learning", "Youth"],
    link: "https://www.theknowledgehouse.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "40",
    type: "online",
    name: "Torrance Evans Newsletter",
    description:
      "Newsletter providing insights, opportunities, and resources for professionals in technology and career development.",
    tags: ["Job Opportunities"],
    link: "https://lnkd.in/gvUc34wF",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "41",
    type: "online",
    name: "Torc",
    description:
      "Developer community and platform providing resources, tools, and networking opportunities for software engineers and developers.",
    tags: ["Community", "Developer Tools", "Programming", "Networking & Events"],
    link: "https://platform.torc.dev/#/r/rArypu30/cp",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "42",
    type: "online",
    name: "Women Coders Network",
    description:
      "Global community supporting women in coding through mentorship, resources, and networking opportunities across all skill levels.",
    tags: ["Diversity & Inclusion", "Women in Tech", "Community", "Mentorship & Guidance"],
    link: "https://womencodersnetwork.com/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "43",
    type: "online",
    name: "Women in Tech Georgia",
    description:
      "Georgia-based community empowering women in technology through networking, mentorship, and professional development opportunities.",
    tags: ["Diversity & Inclusion", "Women in Tech", "Networking & Events"],
    link: "https://women-in-tech.org/ge/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "44",
    type: "online",
    name: "Women In Technology (WIT)",
    description:
      "Organization advancing women in technology through networking, education, mentoring, and advocacy for workplace equality.",
    tags: ["Diversity & Inclusion", "Women in Tech", "Education & Learning", "Advocacy"],
    link: "https://mywit.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "45",
    type: "online",
    name: "Women Who Tech",
    description:
      "Global nonprofit organization bringing together talented and renowned women breaking new ground in technology to transform the world.",
    tags: ["Diversity & Inclusion", "Women in Tech"],
    link: "https://womenwhotech.org/",
    image: "/placeholder.svg?height=200&width=300",
  },
].sort((a, b) => a.name.localeCompare(b.name))

export const sampleTechHubs: Resource[] = [
  {
    id: "19",
    type: "tech-hub",
    name: "Atlanta Tech Park",
    description:
      "A 1.2 million square foot technology park in Peachtree Corners featuring state-of-the-art facilities, innovation labs, and collaborative spaces for tech companies and startups.",
    tags: ["Innovation Labs", "Startups", "Enterprise", "Peachtree Corners"],
    link: "https://www.atlantatechpark.com/",
    image: "/atlanta-tech-park.png",
  },
  {
    id: "20",
    type: "tech-hub",
    name: "Atlanta Tech Village",
    description:
      "The Southeast's largest tech startup hub located in Buckhead, providing workspace, mentorship, and community for over 300 tech companies and entrepreneurs.",
    tags: ["Startups", "Coworking", "Mentorship", "Buckhead"],
    link: "https://www.atlantatechvillage.com/",
    image: "/atlanta-tech-village.png",
  },
  {
    id: "21",
    type: "tech-hub",
    name: "Curiosity Lab",
    description:
      "A smart city living laboratory in Peachtree Corners featuring autonomous vehicle testing, 5G networks, and IoT infrastructure for technology innovation and research.",
    tags: ["Smart City", "Autonomous Vehicles", "5G", "IoT", "Research"],
    link: "https://curiositylabptc.com/",
    image: "/curiosity-lab-smart-city.png",
  },
  {
    id: "22",
    type: "tech-hub",
    name: "Tech Square ATL",
    description:
      "Georgia Tech's innovation district in Midtown Atlanta, connecting students, faculty, and industry partners through cutting-edge research and entrepreneurship programs.",
    tags: ["Georgia Tech", "Research", "Innovation", "Midtown"],
    link: "https://www.techsquareatl.com/",
    image: "/techsquare-atl.png",
  },
  {
    id: "23",
    type: "tech-hub",
    name: "ATDC",
    description:
      "Georgia's technology incubator helping entrepreneurs launch and build successful companies through mentorship, resources, and access to Georgia Tech's research ecosystem.",
    tags: ["Incubator", "Georgia Tech", "Mentorship", "Research"],
    link: "https://atdc.org/",
    image: "/atdc-georgia-tech.png",
  },
  {
    id: "24",
    type: "tech-hub",
    name: "Russell Innovation Center",
    description:
      "Focused on empowering underrepresented entrepreneurs in technology, providing resources, mentorship, and community support for diverse tech startups.",
    tags: ["Diversity", "Entrepreneurship", "Mentorship", "Community"],
    link: "https://russellcenter.org/",
    image: "/russell-innovation-center.png",
  },
]
